Will now call Brukernotifikasjoner
navikt/sendsoknad-boot pull request #137
Opened 2022-09-08 10:13 UTC by sjoblomjsqueed

2022-09-08 12:53 UTC, alpet approved these changes

2022-09-09 07:06 UTC, nils-arne requested changes
Kanseller brukernotifikasjon ved innsending av søknad. 
Opprett ny ettersendingssøknad dersom det er obligatoriske vedlegg som søker skal ettersende. Til denne ettersendingssøknaden skal det opprettes en brukernotifikasjon-Oppgave.

2022-09-09 07:06 UTC, nils-arne commented on sendsoknad-business/src/test/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/InnsendingServiceTest.java
> +        assertEquals(1, brukernotifikasjon.getCallsToNewNotificationAndReset());
Fiks

2022-09-09 07:06 UTC, nils-arne commented on sendsoknad-business/src/test/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/InnsendingServiceTest.java
> +        assertEquals(1, brukernotifikasjon.getCallsToNewNotificationAndReset());
Fiks

2022-09-09 07:06 UTC, nils-arne commented on sendsoknad-business/src/test/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/InnsendingServiceTest.java
> +        assertEquals(1, brukernotifikasjon.getCallsToNewNotificationAndReset());
.....

2022-09-09 07:06 UTC, nils-arne commented on sendsoknad-business/src/test/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/InnsendingServiceTest.java
> +        assertEquals(1, brukernotifikasjon.getCallsToNewNotificationAndReset());
.................

2022-09-09 07:06 UTC, nils-arne commented on sendsoknad-business/src/test/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/InnsendingServiceTest.java
> +        assertEquals(1, brukernotifikasjon.getCallsToNewNotificationAndReset());
............

2022-09-09 07:06 UTC, nils-arne commented on sendsoknad-business/src/test/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/InnsendingServiceTest.java
> +        assertEquals(1, brukernotifikasjon.getCallsToNewNotificationAndReset());
.....................

2022-09-09 07:06 UTC, nils-arne commented on sendsoknad-business/src/test/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/InnsendingServiceTest.java
> +        assertEquals(1, brukernotifikasjon.getCallsToNewNotificationAndReset());
................

2022-09-12 09:43 UTC, alpet commented
"Merk at dersom søker IKKE har har sendt inn alle obligatoriske vedlegg til søknaden, så skal det opprettes en NY brukernotifikasjonsoppgave for ettersendelse av disse. " -

Dette gjenstår.

2022-09-12 12:30 UTC, sjoblomjsqueed commented on sendsoknad-business/src/main/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/SoknadDataFletter.java
> +                brukernotifikasjonService.cancelNotification(behandlingsId, behandlingsId,soknad.erEttersending(),soknad.getAktoerId());
There is already code calling `brukernotifikasjon.newNotification()` in InnsendingService. We should put these two calls next to each other.

2022-09-12 12:31 UTC, sjoblomjsqueed commented on sendsoknad-business/src/main/java/no/nav/sbl/dialogarena/soknadinnsending/business/service/soknadservice/EttersendingService.java
> +        if ("true".equals(sendDirectlyToSoknadsmottaker)) {
We should use `equalsIgnoreCase` instead

2022-09-21 13:44 UTC, alpet approved these changes

2022-09-26 09:26 UTC, alpet commented on nais/sendsoknad-preprod.json
> +	"brukernotifikasjonTjensteUrl": "https://www.dev.nav.no/sendinn",
Dette re intern komponent, hvorfor er inngressen endret ?

2022-09-26 09:29 UTC, sjoblomjsqueed commented on nais/sendsoknad-preprod.json
> +	"brukernotifikasjonTjensteUrl": "https://www.dev.nav.no/sendinn",
Dette er ikke ingressen, men den URL brukeren får på sin brukernotifikasjon.

2022-09-26 12:12 UTC, alpet commented on nais/nais-preprod.yml
> +      value: "/sendsoknad"
Dette kan endre seg , hvis vi har paralel deploy.

2022-09-26 12:16 UTC, sjoblomjsqueed commented on nais/nais-preprod.yml
> +      value: "/sendsoknad"
Aha. Fikset i ny commit

2022-09-29 07:12 UTC, closed without merging